version: "3.9"

services:
  admin-dashboard:
    build:
      context: ./admin-dashboard
    container_name: admin-dashboard
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

  kiosk-interface:
    build:
      context: ./kiosk-interface
    container_name: kiosk-interface
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: kiosk-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin7890@db:5432/kioskdb
      - CORS_ORIGINS=http://localhost:8080,http://localhost:8081
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    # volumes:
    #   - ./backend:/app
    #   - ./backend/generated_docs:/app/generated_docs

  db:
    image: postgres:16
    container_name: kiosk-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin7890
      POSTGRES_DB: kioskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata: